name: Deploy MaliBot DevContainer

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build Compose Containers
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Deploy Project Direct to SSH Host
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.REMOTE_DOCKER_HOST }}
          username: ${{ secrets.REMOTE_DOCKER_USER }}
          key: ${{ secrets.S_PRIVATE }}
          script: |
            git clone https://github.com/PQPMath3ws/mali-discord-bot-poc.git
            cd mali-discord-bot-poc
            echo "APP_PORT=5000\nDATABASE_URL=postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}?schema=public\nDISCORD_BOT_CLIENT_ID=${{ secrets.DISCORD_BOT_CLIENT_ID }}\nDISCORD_BOT_PUBLIC_KEY=${{ secrets.DISCORD_BOT_PUBLIC_KEY }}\nDISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }}\nPOSTGRES_USERNAME=${{ secrets.POSTGRES_USERNAME }}\nPOSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}\nPOSTGRES_HOST=malibot-postgres\nPOSTGRES_PORT=5432\nPOSTGRES_DATABASE=malibot_db" > .env
            docker-compose up -d