name: Deploy MaliBot DevContainer

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build Compose Containers
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Deploy Project Direct to SSH Host
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.REMOTE_DOCKER_HOST }}
          username: ${{ secrets.REMOTE_DOCKER_USER }}
          key: ${{ secrets.S_PRIVATE }}
          script: |
            docker container stop malibot-app malibot-postgres
            docker container rm malibot-app malibot-postgres
            docker image rm mali-discord-bot-poc_malibot-app postgres
            docker volume rm mali-discord-bot-poc_malibot-postgres-data
            sudo rm -f -r mali-discord-bot-poc
            EXPORT APP_PORT=5000
            EXPORT DISCORD_BOT_CLIENT_ID=${{ secrets.DISCORD_BOT_CLIENT_ID }}
            EXPORT DISCORD_BOT_PUBLIC_KEY=${{ secrets.DISCORD_BOT_PUBLIC_KEY }}
            EXPORT DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }}
            EXPORT POSTGRES_USERNAME=${{ secrets.POSTGRES_USERNAME }}
            EXPORT POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            EXPORT POSTGRES_HOST=malibot-postgres
            EXPORT POSTGRES_PORT=5432
            EXPORT POSTGRES_DATABASE=malibot_db
            EXPORT DATABASE_URL=postgresql://${{ secrets.POSTGRES_USERNAME }}:${{ secrets.POSTGRES_PASSWORD }}@malibot-postgres:5432/malibot_db?schema=public
            git clone https://github.com/PQPMath3ws/mali-discord-bot-poc.git
            cd mali-discord-bot-poc
            docker-compose up --build -d